name: test-ulimit

releases:
- name: test-ulimit
  version: latest

instance_groups:
- name: test-ulimit
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: test-ulimit
    release: test-ulimit

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
